name: Release
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: gradleValidation

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Attach Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*.jar
          tag: ${{ github.ref }}
          file_glob: true

      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
